pub const MenuState = enum {
    mainMenu,
    appMenu,
    archiversMenu,
    audioVideoMenu,
    browsersMenu,
    codeEditorsMenu,
    desktopEnvsMenu,
    developerToolsMenu,
    windowManagersMenu,
    driversMenu,
    gameLaunchersMenu,
    messagingMenu,
    kernelMenu,
    terminalsMenu,
    xbpsOrFlatpak,
};
